
CREATE TABLE APP.ROLES (
   ROLE_ID int  NOT NULL,
   ROLE_NAME varchar(50)  NOT NULL,
   ROLE_DESC varchar(100)  NOT NULL,
   LAST_UPDATED_DATE timestamp  NOT NULL,
  CONSTRAINT ROLES_pk PRIMARY KEY (ROLE_ID)
);

CREATE TABLE APP.USERS (
   USER_ID int  NOT NULL,
   ROLE_ID int  NOT NULL,
   USER_NAME varchar(25)  NOT NULL,
   PASSWORD varchar(25)  NOT NULL,
   FIRST_NAME varchar(30)  NOT NULL,
   LAST_NAME varchar(30)  NOT NULL,
   PHONE varchar(15)  NOT NULL,
   EMAIL varchar(30)  NOT NULL,
   ADDRESS varchar(100)  NOT NULL,
   CITY varchar(30)  NOT NULL,
   STATE varchar(30)  NOT NULL,
   COUNTRY varchar(30)  NOT NULL,
   POSTAL_CODE varchar(10)  NOT NULL,
   LAST_UPDATED_DATE timestamp  NOT NULL,
  CONSTRAINT USERS_pk PRIMARY KEY (USER_ID)
);
alter table APP.USERS add constraint ROLES_FK foreign key
(
   ROLE_ID
)references APP.ROLES(ROLE_ID);


CREATE TABLE APP.CATEGORY (
   CATEGORY_ID int  NOT NULL,
   CATEGORY_NAME varchar(30)  NOT NULL,
   CATEGORY_DESCRIPTION varchar(100)  NOT NULL,
   LAST_UPDATED_DATE timestamp  NOT NULL,
  CONSTRAINT CATEGORY_pk PRIMARY KEY (CATEGORY_ID)
);


CREATE TABLE APP.PRODUCT (
   PRODUCT_ID int  NOT NULL,
   CATEGORY_ID int  NOT NULL,
   PRODUCT_CODE varchar(10)  NOT NULL,
   PRODUCT_NAME varchar(50)  NOT NULL,
   PRODUCT_DESCRIPTION varchar(100)  NOT NULL,
   PRODUCT_PRICE decimal(10,2)  NOT NULL,
   IMAGE blob(5000)  NOT NULL,
   LAST_UPDATED_DATE timestamp  NOT NULL,
   ORDER_DETAILS_ORDER_ID int  NOT NULL,
  CONSTRAINT PRODUCT_pk PRIMARY KEY (PRODUCT_ID)
);

alter table APP.PRODUCT add constraint CATEGORY_FK foreign key
(
   CATEGORY_ID
)references APP.CATEGORY(CATEGORY_ID);


CREATE TABLE APP.ORDERS (
   ORDER_ID int  NOT NULL,
   USER_ID int  NOT NULL,
   SHIP_NAME varchar(50)  NOT NULL,
   SHIP_ADDRESS varchar(100)  NOT NULL,
   SHIP_CITY varchar(50)  NOT NULL,
   SHIP_STATE varchar(50)  NOT NULL,
   SHIP_COUNTRY varchar(50)  NOT NULL,
   SHIP_POSTAL_CODE varchar(10)  NOT NULL,
   SHIP_PHONE varchar(15)  NOT NULL,
   SHIP_EMAIL varchar(30)  NOT NULL,
   SHIPPING_DATE timestamp  NOT NULL,
   ORDER_DETAILS_ORDER_ID int  NOT NULL,
  CONSTRAINT ORDERS_pk PRIMARY KEY (ORDER_ID)
);

alter table APP.ORDERS add constraint USERS_FK foreign key
(
   USER_ID
)references APP.USERS(USER_ID);


CREATE TABLE APP.ORDER_DETAILS (
   DETAIL_ID int  NOT NULL,
   ORDER_ID int  NOT NULL,
   PRODUCT_ID int  NOT NULL,
   ORDER_QUANTITY int  NOT NULL,
   ORDER_COST int  NOT NULL,
   ORDER_DISCOUNT int  NOT NULL,
   CONSTRAINT ORDER_DETAILS_pk PRIMARY KEY (DETAIL_ID)
);


